# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXcdhPwy02xCEauMd7wI8jzwvhwsDpzB
"""

# specify path to the dataset
RetiSpec_DATASET_PATH = "/content/gdrive/MyDrive/RetiSpec/Data/Images/RGB+IR Dataset"
# set the input height and width
INPUT_HEIGHT = 64
INPUT_WIDTH = 64
# specify path to the saved model
OUTPUT_PATH = "/content/gdrive/MyDrive/RetiSpec/saved_models/"
CM_PATH = "/content/gdrive/MyDrive/RetiSpec/results/"